service:
  name: "pipelines"
  includedServices: "pipelines"
  gitRepoPath: "PIP/controlPlane"
  devRepositories:
    useInProject: "false"                                                      # Use the dev repositories in the same project as the service
    types:                                                                    # The dev repositories types to create. Note, generic type is created by default
      go: "true"
      maven: "true"
      npm: "true"
      helm: "true"
      docker: "true"

build:
  pipelineFirstStep: "trigger_controlplane_builds"
  ymlFilePath: ".jfrog-pipelines/pipelines-steps.yml"                         # Full path of the build pipeline

release:
  milestoneCronInterval: "0 2 * * *"
  ymlFilePath: ".jfrog-pipelines/release/pipelines.releases.yml"              # Full path of the release pipeline yml file
  valuesYmlPath: ".jfrog-pipelines/release/values.yml"                        # Full path of the release template values.yml file

distribution:
  enabled: "true"                                                             # When enabled distribution pipeline is available for either manual or automatic distribution
  automatic:
    saas: "false"                                                             # Add saas_distribution step to the release pipeline
    onprem: "false"                                                           # Add onprem_distribution step to the release pipeline

features:
  fastRelease: "false"
  skipIdenticalRelease: "false"
  autoTriggerMinor: "false"                                                   # Trigger automatically the release pipeline, from the prerelease pipeline
  releaseOnCommitToMaster: "false"                                            # Automatically release a version for every commit to master
  disableJfrogCoverage: "false"                                               # Disable jfrog release gatekeeper data on collection on the service.
  bitbucketBuilds:
    allowTriggerBogusSuccessfulBuild: "false"                                 # Allows an option to report an empty successful build to bitbucket, so a pull request can be merged
jfdevCiCommonsDefaultVersion: 1.65.*
